// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ... original
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNiAdRpr9_4UPgwAXjgkvhRtSJnN1Azw',
    appId: '1:276414625228:web:aeb60f3a5b81716d5fd969',
    messagingSenderId: '276414625228',
    projectId: 'flutter-upi',
    authDomain: 'flutter-upi.firebaseapp.com',
    storageBucket: 'flutter-upi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK_LDEYrO4MSdQzN5NT9DUmyoyQh4R90E',
    appId: '1:276414625228:android:d5811c594c7917365fd969',
    messagingSenderId: '276414625228',
    projectId: 'flutter-upi',
    storageBucket: 'flutter-upi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDNiAdRpr9_4UPgwAXjgkvhRtSJnN1Azw',
    appId: '1:276414625228:web:b7a2aa9d5370ec0c5fd969',
    messagingSenderId: '276414625228',
    projectId: 'flutter-upi',
    authDomain: 'flutter-upi.firebaseapp.com',
    storageBucket: 'flutter-upi.firebasestorage.app',
  );
}
