name: Build and Deploy Flutter Web to GitHub Pages at UPI-QR-MAKER

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git and cURL
      run: sudo apt-get update && sudo apt-get install -y git curl unzip xz-utils zip cmake 

    # - name: Install Flutter via Snap
    #   run: sudo snap install flutter --classic
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'

    - name: Clone Root Repo (flutter_upi)
      run: |
        git clone https://github.com/MrRohanBatra/flutter_upi.git og_repo
        ls og_repo

    - name: Build Flutter Web & APK (Release)
      working-directory: og_repo/flutter_upi
      run: |
        flutter config --enable-web
        flutter pub get
        flutter build web --release
        flutter build apk --release
    - name: Copy Build to Root Repo Folder (UPI-QR-MAKER)
      run: |
        rm -rf og_repo/UPI-QR-MAKER/*
        mkdir -p og_repo/UPI-QR-MAKER/web
        mkdir -p og_repo/UPI-QR-MAKER/android
        cp -r og_repo/flutter_upi/build/web/* og_repo/UPI-QR-MAKER/web
        cp -r og_repo/flutter_upi/build/app/outputs/flutter-apk/app-release.apk og_repo/UPI-QR-MAKER/android/
    - name: Commit and Push Build to flutter_upi Repo (og_repo)
      working-directory: og_repo
      run: |
        git config user.name "Rohan Batra"
        git config user.email "rohanbatra.in@gmail.com"
        git add UPI-QR-MAKER
        git commit -m "🛠️ Add Flutter Web build to UPI-QR-MAKER folder" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MrRohanBatra/flutter_upi.git HEAD:main

    - name: Clone GitHub Pages Repo (mrrohanbatra.github.io)
      run: |
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MrRohanBatra/mrrohanbatra.github.io.git pages_repo
        ls pages_repo

    - name: Copy Build to GitHub Pages Repo (UPI-QR-MAKER)
      run: |
        rm -rf pages_repo/UPI-QR-MAKER/*
        mkdir -p pages_repo/UPI-QR-MAKER
        cp -r og_repo/flutter_upi/build/web/* pages_repo/UPI-QR-MAKER

    - name: Commit and Push to GitHub Pages
      working-directory: pages_repo
      run: |
        git config user.name "Rohan Batra"
        git config user.email "rohanbatra.in@gmail.com"
        git add .
        git commit -m "🚀 Deploy Flutter Web build to GitHub Pages" || echo "No changes to commit"
        git push