name: Deploy to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
      - name: Disable analytics and enable Flutter
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Push to MrRohanBatra.github.io repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Rohan Batra"
          git config --global user.email "your-email@example.com"

          git clone https://x-access-token:${GH_TOKEN}@github.com/MrRohanBatra/MrRohanBatra.github.io.git

          rm -rf MrRohanBatra.github.io/UPI-QRCODE-MAKER
          mkdir -p MrRohanBatra.github.io/UPI-QRCODE-MAKER
          cp -r build/web/* MrRohanBatra.github.io/UPI-QRCODE-MAKER/

          cd MrRohanBatra.github.io
          git add .
          git commit -m "Auto-deploy UPI QR build to UPI-QRCODE-MAKER"
          git push